{{- $ns := .Values.global.namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ $ns }}
type: Opaque
stringData:
  postgres-user: {{ .Values.database.env.POSTGRESQL_USERNAME | quote }}
  postgres-password: {{ .Values.database.env.POSTGRESQL_PASSWORD | quote }}
  postgres-db: {{ .Values.database.env.POSTGRESQL_DATABASE | quote }}
