apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.monitoring.namespace }}
---
{{- range $ns := .Values.sampleApps.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
---
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.database.namespace }}
