apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.database.namespace }}
data:
  postgres.conf: |
    shared_buffers = 256MB
    max_connections = 100

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Values.database.namespace }}
spec:
  serviceName: postgres
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 999
      containers:
        - name: postgres
          image: {{ .Values.database.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.env.POSTGRES_DB | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.env.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.env.POSTGRES_PASSWORD | quote }}
          ports:
            - containerPort: 5432
              name: pg
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /etc/postgresql
      volumes:
        - name: config
          configMap:
            name: postgres-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.storageClass }}
        storageClassName: "{{ .Values.storage.storageClass }}"
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.database.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.database.namespace }}
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
