{{- $ns := .Values.global.namespace }}
{{- if and (eq .Values.global.platform "kubernetes") (eq .Values.global.expose.type "ingress") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ $ns }}
spec:
  {{- if .Values.global.expose.tlsEnabled }}
  tls: [{ hosts: [ grafana.{{ .Values.global.expose.domain }} ], secretName: grafana-tls }]
  {{- end }}
  rules:
    - host: grafana.{{ .Values.global.expose.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: grafana, port: { number: 3000 } } }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: {{ $ns }}
spec:
  rules:
    - host: prometheus.{{ .Values.global.expose.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: prometheus, port: { number: 9090 } } }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  namespace: {{ $ns }}
spec:
  rules:
    - host: alertmanager.{{ .Values.global.expose.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: alertmanager, port: { number: 9093 } } }
{{- end }}

{{- if and (eq .Values.global.platform "openshift") (eq .Values.global.expose.type "route") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  namespace: {{ $ns }}
spec:
  to: { kind: Service, name: grafana }
  port: { targetPort: 3000 }
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
  namespace: {{ $ns }}
spec:
  to: { kind: Service, name: prometheus }
  port: { targetPort: 9090 }
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: alertmanager
  namespace: {{ $ns }}
spec:
  to: { kind: Service, name: alertmanager }
  port: { targetPort: 9093 }
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: site-a
  namespace: {{ $ns }}
spec:
  to: { kind: Service, name: site-a }
  port: { targetPort: 8080 }
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: site-b
  namespace: {{ $ns }}
spec:
  to: { kind: Service, name: site-b }
  port: { targetPort: 8080 }  
{{- end }}

{{- if eq .Values.global.expose.type "nodeport" }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: {{ $ns }}
spec:
  type: NodePort
  selector: { app: grafana }
  ports:
    - name: web
      port: 3000
      targetPort: 3000
      nodePort: 32000
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: {{ $ns }}
spec:
  type: NodePort
  selector: { app: prometheus }
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 32090
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-nodeport
  namespace: {{ $ns }}
spec:
  type: NodePort
  selector: { app: alertmanager }
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      nodePort: 32093
{{- end }}
