{{- $ns := .Values.global.namespace }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ $ns }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: grafana }
  template:
    metadata:
      labels: { app: grafana }
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
          ports:
            - name: web
              containerPort: 3000
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-dashboards-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: grafana-config
          configMap: { name: grafana-config }
        - name: grafana-datasources
          configMap: { name: grafana-datasources }
        - name: grafana-dashboards
          configMap: { name: grafana-dashboards }
        - name: grafana-dashboards-provisioning
          configMap: { name: grafana-dashboards-provisioning }
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ $ns }}
spec:
  selector: { app: grafana }
  type: ClusterIP
  ports:
    - name: web
      port: 3000
      targetPort: 3000
