{{- $ns := .Values.global.namespace }}
{{- $rel := .Release.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: {{ $ns }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: loki }
  template:
    metadata:
      labels: { app: loki }
    spec:
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          args: ["-config.file=/etc/loki/config.yaml"]
          securityContext:
            runAsNonRoot: true
          ports:
            - { name: http, containerPort: 3100 }
          volumeMounts:
            - { name: config,    mountPath: /etc/loki }
            - { name: loki-data, mountPath: /var/loki }
      volumes:
        - name: config
          configMap: { name: loki-config }
        - name: loki-data
          persistentVolumeClaim:
            claimName: {{ $rel }}-loki-data
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ $ns }}
spec:
  selector: { app: loki }
  ports:
    - { name: http, port: 3100, targetPort: 3100 }
