apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: {{ .Values.monitoring.namespace }}
spec:
  serviceName: loki
  replicas: {{ .Values.loki.replicas }}
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          ports:
            - name: http
              containerPort: 3100
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: data
              mountPath: /var/loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.storageClass }}
        storageClassName: "{{ .Values.storage.storageClass }}"
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.loki.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.monitoring.namespace }}
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
