{{- $ns := .Values.global.namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: site-b-content
  namespace: {{ $ns }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>NGINX Demo</title>
      <style>
        body {
          background-color: #1e90ff;
          color: white;
          font-family: Arial, sans-serif;
          text-align: center;
          padding-top: 10%;
          display: flex;
          flex-direction: column;
          justify-content: center;          
        }
        h1 { font-size: 48px; }
        p  { font-size: 24px; }
      </style>
    </head>
    <body>
      <h1>NGINX is running</h1>
      <p><strong>Pod Name:</strong> $POD_NAME</p>
      <p><strong>Pod IP:</strong> $POD_IP</p>
      <p>You have hit the country <strong>Germany</strong></p>
    </body>
    </html>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: site-b-nginx-conf
  namespace: {{ $ns }}
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri /index.html;
      }

      location /stub_status {
        stub_status;
        allow 127.0.0.1;
        deny all;
      }      
    }

---

{{- $ns := .Values.global.namespace }}
{{- $rel := .Release.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-b
  namespace: {{ $ns }}
spec:
  replicas: 1
  selector: { matchLabels: { app: site-b } }
  template:
    metadata:
      labels: { app: site-b }
    spec:
      containers:
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.5.1
          args:
            - "-nginx.scrape-uri=http://127.0.0.1:8080/stub_status"
          ports:
            - containerPort: 9113       
        - name: nginx
          image: nginx:1.25-alpine
          # Validate config then start in foreground
          command: ["sh","-c","envsubst < /templates/index.html > /usr/share/nginx/html/index.html && nginx -t && exec nginx -g 'daemon off;'"]
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 8080 
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP                        
          volumeMounts:
            - { name: nginx-main, mountPath: /etc/nginx/nginx.conf, subPath: nginx.conf }   # <—
            - { name: site-conf, mountPath: /etc/nginx/conf.d/default.conf, subPath: default.conf } 
            - name: web-template
              mountPath: /templates 
            - { name: web-runtime,    mountPath: /usr/share/nginx/html }
            - { name: cache,  mountPath: /var/cache/nginx }
      volumes:
        - { name: nginx-main, configMap: { name: nginx-main-config } }  
        - { name: site-conf, configMap: { name: site-b-nginx-conf } }  # or site-b-nginx-status                            # <—
        - { name: web-template, configMap: { name: site-b-content } }       # or site-b-content
        - name: web-runtime
          emptyDir: {}
        - name: cache
          emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: site-b
  namespace: {{ $ns }}
spec:
  selector: { app: site-b }
  ports:
    - { name: http,    port: 80,   targetPort: 8080 }
    - { name: metrics, port: 9113, targetPort: 9113 }
