{{- if eq .Values.global.platform "openshift" }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: promtail-scc
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
allowHostNetwork: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
requiredDropCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Values.monitoring.namespace }}:promtail
volumes:
  - configMap
  - emptyDir
  - hostPath
  - secret
  - persistentVolumeClaim
{{- end }}
